import type { Metadata } from "next";
import Navbar from "../components/Navbar";

export const metadata: Metadata = {
    title: "Socialflow",
    description: "Generated by create next app",
};

export default function DashboardLayout({
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>) {
    return (
        <div className="bg-slate-200 sm:px-2 sm:py-2 gap-4">
            <Navbar />
            <div className="p-2 md:h-[85vh] h-screen overflow-auto max-sm:pt-16">
                {children}
            </div>
        </div>
    );
}
